# Generated by update.sh
{ fetchurl }:

{
  "curl-8_7_1.tar.gz" = fetchurl {
    url = "https://github.com/curl/curl/archive/curl-8_7_1.tar.gz";
    hash = "sha256-DkbIVvUXYCw0e7X+W3MXT47nmLyH8alyNclXYfdfzCg=";
  };

  "brotli-1.1.0.tar.gz" = fetchurl {
    url = "https://github.com/google/brotli/archive/refs/tags/v1.1.0.tar.gz";
    hash = "sha256-5yCmyilCi4A/StFlNxdx9TmPq6OX7fZ3iDehhZnqE/8=";
  };

  "boringssl-cd95210465496ac2337b313cf49f607762abe286.zip" = fetchurl {
    url = "https://github.com/google/boringssl/archive/cd95210465496ac2337b313cf49f607762abe286.zip";
    hash = "sha256-D40cQAhqz8jlP95T+kZFIAf/K9Pi5Ig268+eNCoAKl0=";
  };

  "nghttp2-1.63.0.tar.bz2" = fetchurl {
    url = "https://github.com/nghttp2/nghttp2/releases/download/v1.63.0/nghttp2-1.63.0.tar.bz2";
    hash = "sha256-YHsXRVTSKoKLxTLR1zT+D3KbXV7SB/LxLpamLoPynFU=";
  };
}
