# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Avalonia";
    version = "0.10.13";
    hash = "sha256-w+6Qx94BkFBZPaXIcHhmqvNV8L9btc2alKgrL3czxLU=";
  })
  (fetchNuGet {
    pname = "Avalonia.Angle.Windows.Natives";
    version = "2.1.0.2020091801";
    hash = "sha256-ahDcJNCqlNniItcat7owREQ0hfIwMWFNhnDu89lAVRI=";
  })
  (fetchNuGet {
    pname = "Avalonia.AvaloniaEdit";
    version = "0.10.12.2";
    hash = "sha256-3J5ez4lPAJfr/N4CgWbb98DjYdi5fez669I61sOZyOo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.DataGrid";
    version = "0.10.13";
    hash = "sha256-GdGEUBjbyiVYETWiyAtHd9zrBTgZ3eH5M3txVqgAhPo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Desktop";
    version = "0.10.13";
    hash = "sha256-3Bwxi/dL6fHxBw5gBFHIIUcKw4ztVPCHAOh57jI0QPg=";
  })
  (fetchNuGet {
    pname = "Avalonia.Diagnostics";
    version = "0.10.13";
    hash = "sha256-LcZMX8K0xIPlsvytWviaqTnmdIa/QCfVCpXyd/jIcIY=";
  })
  (fetchNuGet {
    pname = "Avalonia.FreeDesktop";
    version = "0.10.13";
    hash = "sha256-V6KUKOKHOqhJz6yF3cAx/imdiZL3ufo3V0w5Ed5//qE=";
  })
  (fetchNuGet {
    pname = "Avalonia.Markup.Xaml.Loader";
    version = "0.10.13";
    hash = "sha256-Mxm3k3P5696zf+BWwLZzJ1mYH8gKD5buwpG2eDsx+aA=";
  })
  (fetchNuGet {
    pname = "Avalonia.Native";
    version = "0.10.13";
    hash = "sha256-6sNtI9dQ7XlXoo16nvuxYAyJbIgH41alv4k/5qa/YqE=";
  })
  (fetchNuGet {
    pname = "Avalonia.Remote.Protocol";
    version = "0.10.13";
    hash = "sha256-3qtFuouVpHjHx7K4cukwU9WcDObwK3HSTiXG1QxsE0g=";
  })
  (fetchNuGet {
    pname = "Avalonia.Skia";
    version = "0.10.13";
    hash = "sha256-tB7FeQ/27phvrTtVBZZN2O3h/j+Zk4qOwANUYgIHvkw=";
  })
  (fetchNuGet {
    pname = "Avalonia.Win32";
    version = "0.10.13";
    hash = "sha256-dNqCvmq2JENsCKgJ6HRthbD5OuQymmOxbQfYYHMO1Es=";
  })
  (fetchNuGet {
    pname = "Avalonia.X11";
    version = "0.10.13";
    hash = "sha256-kHdwSUA5St4tQ+M2agmUHU21GDEjopIwwuR12iRMHfk=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "2.8.2-preview.178";
    hash = "sha256-dtvXNjVSU1WZ4kFsT6VV56R8iGMPHtdM09dfeejnttw=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Linux";
    version = "2.8.2-preview.178";
    hash = "sha256-Vyy8zgtqw1uLJTbWNTS+wt/7yNuO4qzYU5a91Sf1ApA=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "2.8.2-preview.178";
    hash = "sha256-YqGYQttBmNRCmkSS+JRfqTsPnuMdKxkYU9ctS5mKFV0=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.WebAssembly";
    version = "2.8.2-preview.178";
    hash = "sha256-QAwWpNc03Vh2RSqIW0xE/rmQCvl/IWs87QREqZNXMtk=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "2.8.2-preview.178";
    hash = "sha256-J9exQ3FxRHMF8tHTc4zhjYGQ6eBYb4ZKwWhzk2L0uuQ=";
  })
  (fetchNuGet {
    pname = "ICSharpCode.Decompiler";
    version = "7.1.0.6543";
    hash = "sha256-huQuhcbu2AOSw3XaOc84qGWfhmcNrpiexuo01oqWKvc=";
  })
  (fetchNuGet {
    pname = "ICSharpCode.Decompiler";
    version = "7.2.1.6856";
    hash = "sha256-ap3Uq6AwYjO7FbhAm/JjG9YUAv9vWYVggHQk+l9G5qc=";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "10.3.0";
    hash = "sha256-6I/8HtwvEK0JLgRcSrCzCtUfMylj88s5JNcl9ZDoLb8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "2.9.6";
    hash = "sha256-ioxUTmJndOyBc0vpk+my94PyL1IAW7lRjg7gy4ELuaI=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "3.4.0";
    hash = "sha256-XNcdi5TmIOBG5tNCotb+xrxhXCsXln/H5MzHTegzNos=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "3.4.0";
    hash = "sha256-PkUV5IZo2vlGr0sx2abP/dyz7SRm9vgYV32VpDijHmY=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Scripting";
    version = "3.4.0";
    hash = "sha256-jxDRlGE4+Ltf2KbVcVKXWEZBmg5qNr9QPyhx29MHTsA=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Scripting.Common";
    version = "3.4.0";
    hash = "sha256-wlXyB2/afWocrB2IOFfCrme/Tv3edDQ35eJNzK/Fr6Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.0.1";
    hash = "sha256-0huoqR2CJ3Z9Q2peaKD09TV3E6saYSqDGZ290K8CrH8=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.3.0";
    hash = "sha256-a3dAiPaVuky0wpcHmpTVtAQJNGZ2v91/oArA+dpJgj8=";
  })
  (fetchNuGet {
    pname = "Microsoft.DiaSymReader";
    version = "1.4.0";
    hash = "sha256-TaTOMcE3uoRVHTDFbUvJuZ6j/VrT4QmI+jKQVC3UKVI=";
  })
  (fetchNuGet {
    pname = "Microsoft.DiaSymReader.Converter.Xml";
    version = "1.1.0-beta2-22164-02";
    hash = "sha256-1yVpwvqSHOySeEthoQbtzZl9lVIKJRvsPP6D2wdRELk=";
    url = "https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.diasymreader.converter.xml/1.1.0-beta2-22164-02/microsoft.diasymreader.converter.xml.1.1.0-beta2-22164-02.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.DiaSymReader.Native";
    version = "17.0.0-beta1.21524.1";
    hash = "sha256-ejgD24wlL/7UkpZGd39KoVEG6ABg4y44Oovt//qAWj0=";
  })
  (fetchNuGet {
    pname = "Microsoft.DiaSymReader.PortablePdb";
    version = "1.7.0-beta-21525-03";
    hash = "sha256-00MFnstDAX1YxKrJ6qgsEYqSs9P+jsSkDMbF9mQGZ0k=";
    url = "https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.diasymreader.portablepdb/1.7.0-beta-21525-03/microsoft.diasymreader.portablepdb.1.7.0-beta-21525-03.nupkg";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.0.1";
    hash = "sha256-mZotlGZqtrqDSoBrZhsxFe6fuOv5/BIo0w2Z2x0zVAU=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.1";
    hash = "sha256-8hLiUKvy/YirCWlFwzdejD2Db3DaXhHxT7GSZx/znJg=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    hash = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8tyemYcR0Yro=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.1.2";
    hash = "sha256-gYQQO7zsqG+OtN4ywYQyfsiggS2zmxw4+cPXlK+FB5Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    hash = "sha256-LIcg1StDcQLPOABp4JRXIs837d7z0ia6+++3SF3jl1c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.0.1";
    hash = "sha256-lxxw/Gy32xHi0fLgFWNj4YTFBSBkjx5l6ucmbTyf7V4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.3";
    hash = "sha256-WLsf1NuUfRWyr7C7Rl9jiua9jximnVvzy6nk2D2bVRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Composition";
    version = "17.1.20";
    hash = "sha256-2g1nDS7EJb4lbww6GUhhnMzwgVIYu0PFsxYw/HNnCwk=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Composition.Analyzers";
    version = "17.1.20";
    hash = "sha256-6uxhZxf0rIYWprcPTGJK+JBTAyMB9fHcXQDivYJE1ZE=";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Validation";
    version = "17.0.34";
    hash = "sha256-9/m0FQx9jvJfUnVWLKKlC/6xBsUA3qHV0Lp1w98xiiY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.0.1";
    hash = "sha256-B4t5El/ViBdxALMcpZulewc4j/3SIXf71HhJWhm4Ctk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-mBNDmPXNTW54XLnPAUwBRvkIORFM7/j0D0I2SyQPDEg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "4.0.0";
    hash = "sha256-M/06F/Z2wTHCh4pZOgtCjUGLD1FJXEJKCmzOeFMl7uo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    hash = "sha256-9kylPGfKZc58yFqNKa77stomcoNnMeERXozWJzDcUIA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "4.5.0";
    hash = "sha256-WFqy842DMQG4W1H2ewXWflfBJ+lQf/LwP0KI4OfY0zo=";
  })
  (fetchNuGet {
    pname = "Mono.Cecil";
    version = "0.11.3";
    hash = "sha256-QxJcRt3eYy7R0mc25F/hM5n4qVqBAlZChsEKn+Y9nXU=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.0";
    hash = "sha256-ExWI1EKDCRishcfAeHVS/RoJphqSqohmJIC/wz3ZtVo=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.1";
    hash = "sha256-iNan1ix7RtncGWC9AjAZ2sk70DoxOsmEOgQ10fXm4Pw=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "9.0.1";
    hash = "sha256-mYCBrgUhIJFzRuLLV9SIiIFHovzfR8Uuqfg6e08EnlU=";
  })
  (fetchNuGet {
    pname = "NuGet.Client";
    version = "4.2.0";
    hash = "sha256-NLtl4pwVkXt3oz+uR+CUUBQvbepdjJciBJV1EP3hZOg=";
  })
  (fetchNuGet {
    pname = "NuGet.Common";
    version = "4.2.0";
    hash = "sha256-jG8OyEoRvdNBROQCXmvS8Ficj+iwZ/GVKI51NW2aC0k=";
  })
  (fetchNuGet {
    pname = "NuGet.ContentModel";
    version = "4.2.0";
    hash = "sha256-dVtuqzJXCjHRcmQQHkGJhlyjZrvKqZke/yNA/lr9CaU=";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "4.2.0";
    hash = "sha256-Y2l+JNWBl+7PmMeTfG9eQ07VdTLpKQDol407gCd6nzc=";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging";
    version = "4.2.0";
    hash = "sha256-4yKtt4dDCK+Vo9loFuU5nZEXu2qIncYfa4x+0InPA70=";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging.Core";
    version = "4.2.0";
    hash = "sha256-0zW9Y0qG74hYHny8Dn+PPaAwwBHfnNCXF2F1zf3Xt4U=";
  })
  (fetchNuGet {
    pname = "NuGet.Packaging.Core.Types";
    version = "4.2.0";
    hash = "sha256-cpYrGQBjaNXymWKv1SKNJwK+Elv+4pUFM2RhXfT6Lww=";
  })
  (fetchNuGet {
    pname = "NuGet.Repositories";
    version = "4.2.0";
    hash = "sha256-lwLs4E4jKDj1vyRnXXuKEL0LHkuC3GFKa/kVhI+kKHA=";
  })
  (fetchNuGet {
    pname = "NuGet.RuntimeModel";
    version = "4.2.0";
    hash = "sha256-XSlsfjWUG1yLhyWNnaIil6cAU7FfmMgi1suU+QXnqUw=";
  })
  (fetchNuGet {
    pname = "NuGet.Versioning";
    version = "4.2.0";
    hash = "sha256-o4kfSRAPcvvbrvp2K87g0vnZZ7WTjvv9eYbC9iBZp9c=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-8yLKFt2wQxkEf7fNfzB+cPUCjYn2qbqNgQ1+EeY2h/I=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-dsmTLGvt8HqRkDWP8iKVXJCS+akAzENGXKPV18W2RgI=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-AYh39tgXJVFu8aLi9Y/4rK8yWMaza4S4eaxjfcuEEL4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-6MYj0RmLh4EVqMtO/MRqBi0HOn5iG4x9JimgCCJ+EFM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-BgHxXCIbicVZtpgMimSXixhFC3V+p5ODqeljDjO8hCs=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.0.0";
    hash = "sha256-bmaM0ovT4X4aqDJOR255Yda/u3fmHZskU++lMnsy894=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-DWnXs4vlKoU6WxxvCArTJupV6sX3iBbZh8SbqfHace8=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.0.1";
    hash = "sha256-5nWnTQrA1T6t9r8MqIiV4yTNu+IH0of2OX1qteoS+8E=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.3.0";
    hash = "sha256-c556PyheRwpYhweBjSfIwEyZHnAUB8jWioyKEcp/2dg=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography";
    version = "4.0.0";
    hash = "sha256-6Q8eYzC32BbGIiTHoQaE6B3cD81vYQcH5SCswYRSp0w=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-2IhBv0i6pTcOyr8FFIyfPEaaCHUmJZ8DYwLUwJ+5waw=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-serkd4A7F6eciPiPJtUyJyxzdAtupEcWIZQ9nptEzIM=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-LZb23lRXzr26tRS5aA0xyB08JxiblPDoA7HBvn6awXg=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Console";
    version = "4.3.1";
    hash = "sha256-dxyn/1Px4FKLZ2QMUrkFpW619Y1lhPeTiGLWYM6IbpY=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-Pf4mRl6YDK2x2KMh0WdyNgv0VUNdSKVDLlHqozecy5I=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-pHJ+I6i16MV6m77uhTC6GPY6jWGReE3SSP3fVB59ti0=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-IvgOeA2JuBjKl5yAVGjPYMPDzs9phb3KANs95H9v1w4=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.0-preview.178";
    hash = "sha256-05L+H81OBZDMxn/DWgJ3m8tRtRoSRn6t6nGJZTQJTxg=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.0-preview.178";
    hash = "sha256-XM/h5oWVGRBN68BLG6nLxlFW3j+juG0FGHTQUGRQbx4=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.0-preview.178";
    hash = "sha256-8bGU2DPZMRmGv+0nMswUQ4AJzFo/QWEzwd5oxrot6ZI=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.WebAssembly";
    version = "2.88.0-preview.178";
    hash = "sha256-VRMWi3Vum53PaZDAgXnxwukINq8gaScRVfruMMtjVSY=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.0-preview.178";
    hash = "sha256-1KJmFxYZ6p+vJNB/p2ShBcSCaIF4PXv5dmNTAQ6NLDo=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.1.0";
    hash = "sha256-v6YfyfrKmhww+EYHUq6cwYUMj00MQ6SOfJtcGVRlYzs=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.3.0";
    hash = "sha256-yg95LNQOwFlA1tWxXdQkVyJqT4AnoDc+ACmrNvzGiZg=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.0.0";
    hash = "sha256-+YUymoyS0O+xVyF2+LiAdZlMww8nofPN4ja9ylYqRo8=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.3.0";
    hash = "sha256-XqZWb4Kd04960h4U9seivjKseGA/YEIpdplfHYHQ9jk=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.0.11";
    hash = "sha256-puoFMkx4Z55C1XPxNw3np8nzNGjH+G24j43yTIsDRL0=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.0.12";
    hash = "sha256-zIEM7AB4SyE9u6G8+o+gCLLwkgi6+3rHQVPdn/dEwB8=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    hash = "sha256-KMY5DfJnDeIsa13DpqvyN8NkReZEMAFnlmNglVoFIXI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.5.0";
    hash = "sha256-BliqYlL9ntbMXo5d7NUrKXwYN+PqdyqDIS5bp4qVr7Q=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.6.0";
    hash = "sha256-gnu+8nN48GAd4GRgeB5cAQmW7VnCubL/8h7zO377fd0=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "5.0.0";
    hash = "sha256-GdwSIjLMM0uVfE56VUSLVNgpW0B//oCeSFj8/hSlbM8=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.5.0";
    hash = "sha256-15yE2NoT9vmL9oGCaxHClQR1jLW1j1ef5hHMg55xRso=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Composition";
    version = "6.0.0";
    hash = "sha256-7JyYbqWl1NHTNMJW12g6TtYfkemI52nOnX7OHWvp7ps=";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "6.0.0";
    hash = "sha256-H5TnnxOwihI0VyRuykbOWuKFSCWNN+MUEYyloa328Nw=";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "6.0.0";
    hash = "sha256-03DR8ecEHSKfgzwuTuxtsRW0Gb7aQtDS4LAYChZdGdc=";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "6.0.0";
    hash = "sha256-a3DZS8CT2kV8dVpGxHKoP5wHVKsT+kiPJixckpYfdQo=";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "6.0.0";
    hash = "sha256-fpoh6WBNmaHEHszwlBR/TNjd85lwesfM7ZkQhqYtLy4=";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "6.0.0";
    hash = "sha256-nGZvg2xYhhazAjOjhWqltBue+hROKP0IOiFGP8yMBW8=";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "6.0.0";
    hash = "sha256-4uAETfmL1CvGjHajzWowsEmJgTKnuFC8u9lbYPzAN3k=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.0.0";
    hash = "sha256-jtZfT/TpJtLisV/y5Mk3IfCpE79zwhBYXtyGP9jC3Xo=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.3.0";
    hash = "sha256-Xh3PPBZr0pDbDaK8AEHbdGz7ePK6Yi1ZyRWI1JM6mbo=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.0.11";
    hash = "sha256-P+rSQJVoN6M56jQbs76kZ9G3mAWFdtF27P/RijN8sj4=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.0.0";
    hash = "sha256-dYh9UoFesuGcHY+ewsI+z2WnNy+bwHPsHQ3t85cbzNg=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.3.0";
    hash = "sha256-OFJRb0ygep0Z3yDBLwAgM/Tkfs4JCDtsNhwDH9cd1Xw=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Process";
    version = "4.1.0";
    hash = "sha256-OgW6ogQ+oYADYS0PHmwXdhrOKQJpqXlwzSvmfjTLNBg=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.0.1";
    hash = "sha256-vSBqTbmWXylvRa37aWyktym+gOpsvH43mwr6A962k6U=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-gVOv1SK6Ape0FQhCVlNOd9cvQKBvMxRX9K0JPVi8w0Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.1.0";
    hash = "sha256-JA0jJcLbU3zh52ub3zweob2EVHvxOqiC6SCYHrY5WbQ=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-hCETZpHHGVhPYvb4C0fh4zs+8zv4GPoixagkLZjpa9Q=";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "4.5.0";
    hash = "sha256-DLYGJraIfSj0Zmpi2H5Am2AsZ+kP5UVGdjakqj9Q2E4=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.0.11";
    hash = "sha256-qWqFVxuXioesVftv2RVJZOnmojUvRjb7cS3Oh3oTit4=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.3.0";
    hash = "sha256-k75gjOYimIQtLBD5NDzwwi3ZMUBPRW3jmc3evDMMJbU=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.0.11";
    hash = "sha256-rbSgc2PIEc2c2rN6LK3qCREAX3DqA2Nq1WcLrZYsDBw=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.0.1";
    hash = "sha256-EJN3LbN+b0O9Dr2eg7kfThCYpne0iJ/H/GIyUTNVYC8=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-uNOD0EOVFgnS2fMKvMiEtI9aOw00+Pfy/H+qucAQlPc=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.0.1";
    hash = "sha256-zLtkPryJwqTGcJqMC6zoMMvMrT+aAL5GoumjmMtqUEI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    hash = "sha256-mmJWA27T0GRVuFP9/sj+4TrR4GJWrzNIk2PDrbr7RQk=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.1.0";
    hash = "sha256-V6oyQFwWb8NvGxAwvzWnhPxy9dKOfj/XBM3tEC5aHrw=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-f5PrQlQgj5Xj2ZnHxXW8XiOivaBvfqDao9Sb6AVinyA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.0.1";
    hash = "sha256-An0Twb9JODl/nuVm6MR0kJ3aj4WxGpI/1/vVp5b94kA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.3.0";
    hash = "sha256-WQl+JgWs+GaRMeiahTFUbrhlXIHapzcpTFXbRvAtvvs=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.0.1";
    hash = "sha256-4VKXFgcGYCTWVXjAlniAVq0dO3o5s8KHylg2wg2/7k0=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-vNIYnvlayuVj0WfRfYKpDrhDptlhp1pN8CYmlVd2TXw=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.0.1";
    hash = "sha256-IpigKMomqb6pmYWkrlf0ZdpILtRluX2cX5sOKVW0Feg=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.1.0";
    hash = "sha256-ZQpFtYw5N1F1aX0jUK3Tw+XvM5tnlnshkTCNtfVA794=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.1.0";
    hash = "sha256-7zqB+FXgkvhtlBzpcZyd81xczWP0D3uWssyAGw3t7b4=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.1.0";
    hash = "sha256-y6PnGuObJvOkhl9CXNFJQcV3SXuEz5yRLOCxGGTEucQ=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.0";
    hash = "sha256-UoBB7WPDp2Bne/fwxKF0nE8grJ6FzTMXdT/jfsphj8Q=";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.3.0";
    hash = "sha256-eGZwCBExWsnirWBHyp2sSSSXp6g7I6v53qNmwPgtJ5c=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.0.11";
    hash = "sha256-2YSijNhCdw/ZU2yfH7vE+ReA8pgxRCXPnWr+ab36v4M=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-MY7Z6vOtFMbEKaLW9nOSZeAjcWpwCtdO7/W1mkGZBzE=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.1.0";
    hash = "sha256-muK7oXIX7ykqhXskuUt0KX6Hzg5VogJhUS0JiOB2BY0=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-il7dr5VT/QWDg/0cuh+4Es2u8LY//+qqiY9BZmYxSus=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    hash = "sha256-qdSTIFgf2htPS+YhLGjAGiLN8igCYJnCCo6r78+Q+c8=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.0.12";
    hash = "sha256-MudZ/KYcvYsn2cST3EE049mLikrNkmE7QoUoYKKby+s=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "5.0.0";
    hash = "sha256-M5Z8pw8rVb8ilbnTdaOptzk5VFd5DlKa7zzCpuytTtE=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.1.0";
    hash = "sha256-idZHGH2Yl/hha1CM4VzLhsaR8Ljo/rV7TYe7mwRJSMs=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.0.1";
    hash = "sha256-F1MvYoQWHCY89/O4JBwswogitqVvKuVfILFqA7dmuHk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.7.0";
    hash = "sha256-Fw/CSRD+wajH1MqfKS3Q/sIrUH7GN4K+F+Dx68UPNIg=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.0.1";
    hash = "sha256-YG+eJBG5P+5adsHiw/lhJwvREnvdHw6CJyS8ZV4Ujd0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.0.1";
    hash = "sha256-uVvNOnL64CPqsgZP2OLqNmxdkZl6Q0fTmKmv9gcBi+g=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.0.1";
    hash = "sha256-NsfmzM9G/sN3H8X2cdnheTGRsh7zbRzvegnjDzDH/FQ=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "5.0.0";
    hash = "sha256-Wo+MiqhcP9dQ6NuFGrQTw6hpbJORFwp+TBNTq2yhGp8=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.0.1";
    hash = "sha256-SFSfpWEyCBMAOerrMCOiKnpT+UAWTvRcmoRquJR6Vq0=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.1.0";
    hash = "sha256-R0YZowmFda+xzKNR4kKg7neFoE30KfZwp/IwfRSKVK4=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    hash = "sha256-4U4/XNQAnddgQIHIJq3P2T80hN0oPdU2uCeghsDTWng=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.7.0";
    hash = "sha256-GEtCGXwtOnkYejSV+Tfl+DqyGq5jTUaVyL9eMupMHBM=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.0.1";
    hash = "sha256-cZ2/3/fczLjEpn6j3xkgQV9ouOVjy4Kisgw5xWw9kSw=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.1.0";
    hash = "sha256-FViNGM/4oWtlP6w0JC0vJU+k9efLKZ+yaXrnEeabDQo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.1";
    hash = "sha256-R9T68AzS1PJJ7v6ARz9vo88pKL1dWqLOANg4pkQjkA0=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.2";
    hash = "sha256-8eUXXGWO2LL7uATMZye2iCpQOETn2jCcjUhG6coR5O8=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.6.0";
    hash = "sha256-FTjQeMuvqnKxpoVsVh/OlQ21NMaZiFtOdv7VdZ+Iv3Y=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.1.0";
    hash = "sha256-X7DZ5CbPY7jHs20YZ7bmcXs9B5Mxptu/HnBUvUnNhGc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.1";
    hash = "sha256-xll/AF6sF1soQ15prAPIVHSH69CiL4E9OHVDHyrm868=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.0.1";
    hash = "sha256-j2QgVO9ZOjv7D1het98CoFpjoYgxjupuIhuBUmLLH7w=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.1.0";
    hash = "sha256-QceAYlJvkPRJc/+5jR+wQpNNI3aqGySWWSO30e/FfQY=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.0.0";
    hash = "sha256-5j53amb76A3SPiE3B0llT2XPx058+CgE7OXL4bLalT4=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    hash = "sha256-MYpl6/ZyC6hjmzWRIe+iDoldOMW1mfbwXsduAnXIKGA=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.0.1";
    hash = "sha256-1pJt5ZGxLPTX1mjOi8qZPXyyOMkYV0NstoUCv91HYPg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    hash = "sha256-P5jHCgMbgFMYiONvzmaKFeOqcAIDPu/U8bOVrNPYKqc=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Serialization.Primitives";
    version = "4.1.1";
    hash = "sha256-80B05oxJbPLGq2pGOSl6NlZvintX9A1CNpna2aN0WRA=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    hash = "sha256-ueSG+Yn82evxyGBnE49N4D+ngODDXgornlBtQ3Omw54=";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.3.0";
    hash = "sha256-Fua/rDwAqq4UByRVomAxMPmDBGd5eImRqHVQIeSxbks=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.2.0";
    hash = "sha256-BelNIpEyToEp/VYKnje/q1P7KNEpQNtOzGPU18pLGpE=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    hash = "sha256-tAJvNSlczYBJ3Ed24Ae27a55tq/n4D3fubNQdwcKWA8=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.2.0";
    hash = "sha256-7F+m3HnmBsgE4xWF8FeCGlaEgQM3drqA6HEaQr6MEoU=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.3.0";
    hash = "sha256-u17vy6wNhqok91SrVLno2M1EzLHZm6VMca85xbVChsw=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.0.0";
    hash = "sha256-WHyR6vVK3zaT4De7jgQFUar1P5fiX9ECwiVkJDFFm7M=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.3.0";
    hash = "sha256-oefdTU/Z2PWU9nlat8uiRDGq/PGZoSPRgkML11pmvPQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.0.0";
    hash = "sha256-ZO7ha39J5uHkIF2RoEKv/bW/bLbVvYMO4+rWyYsKHik=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    hash = "sha256-Yuge89N6M+NcblcvXMeyHZ6kZDfwBv3LPMDiF8HhJss=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.0.0";
    hash = "sha256-mLijAozynzjiOMyh2P5BHcfVq3Ovd0T/phG08SIbXZs=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-DL+D2sc2JrQiB4oAcUggTFyD8w3aLEjJfod5JPe+Oz4=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.0.0";
    hash = "sha256-sEdPftfTxQd/8DpdpqUZC2XWC0SjVCPqAkEleLl17EQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    hash = "sha256-fnFi7B3SnVj5a+BbgXnbjnGNvWrCEU6Hp/wjsjWz318=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.1.0";
    hash = "sha256-sBUUhJP+yYDXvcjNMKqNpn8yzGUpVABwK9vVUvYKjzI=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    hash = "sha256-MG3V/owDh273GCUPsGGraNwaVpcydupl3EtPXj6TVG0=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.3.0";
    hash = "sha256-rjudVUHdo8pNJg2EVEn0XxxwNo5h2EaYo+QboPkXlYk=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.3.0";
    hash = "sha256-mbdLVUcEwe78p3ZnB6jYsizNEqxMaCAWI3tEQNhRQAE=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.7.0";
    hash = "sha256-rWBM2U8Kq3rEdaa1MPZSYOOkbtMGgWyB8iPrpIqmpqg=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    hash = "sha256-CBOQwl9veFkrKK2oU8JFFEiKIh/p+aJO+q9Tc2Q/89Y=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.0.11";
    hash = "sha256-PEailOvG05CVgPTyKLtpAgRydlSHmtd5K0Y8GSHY2Lc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.5.1";
    hash = "sha256-PIhkv59IXjyiuefdhKxS9hQfEwO9YWRuNudpo53HQfw=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-vufHXg8QAKxHlujPHHcrtGwAqFmsCD6HKjfDAiHyAYc=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.1.0";
    hash = "sha256-x6OQN6MCN7S0fJ6EFTfv4rczdUWjwuWE9QQ0P6fbh9c=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.0";
    hash = "sha256-VLCk1D1kcN2wbAe3d0YQM/PqCsPHOuqlBY1yd2Yo+K0=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.0.11";
    hash = "sha256-mob1Zv3qLQhQ1/xOLXZmYqpniNUMCfn02n8ZkaAhqac=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.0.11";
    hash = "sha256-5SLxzFg1df6bTm2t09xeI01wa5qQglqUwwJNlQPJIVs=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "5.0.0";
    hash = "sha256-Hi7MpNVXe5lZmQkty3BqIC2kyknskFLNdkkWy1+NDgk=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.0.0";
    hash = "sha256-+YdcPkMhZhRbMZHnfsDwpNbUkr31X7pQFGxXYcAPZbE=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.3.0";
    hash = "sha256-X2hQ5j+fxcmnm88Le/kSavjiGOmkcumBGTZKBLvorPc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.3";
    hash = "sha256-8TglbC6KBHlDeSfgr6d5dGn7wu8td4XERl2JUyo0+Tw=";
  })
  (fetchNuGet {
    pname = "System.Threading.Thread";
    version = "4.0.0";
    hash = "sha256-7EtSJuKqcW107FYA5Ko9NFXEWUPIzNDtlfKaQV2pvb8=";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.0.10";
    hash = "sha256-/fowWjM/0ZZFC1Rwu0i5N71iRxV2JOd3jQV2Jn0wuTk=";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.3.0";
    hash = "sha256-wW0QdvssRoaOfQLazTGSnwYTurE4R8FxDx70pYkL+gg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.0.1";
    hash = "sha256-5lU6zt1O9JDSPr2KAHw4BYgysHnt0yyZrMNa5IIjxZY=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-pmhslmhQhP32TWbBzoITLZ4BoORBqYk25OWbru04p9s=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    hash = "sha256-niH6l2fU52vAzuBlwdQMw0OEoRS/7E1w5smBFoqSaAI=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.0.11";
    hash = "sha256-haZAFFQ9Sl2DhfvEbdx2YRqKEoxNMU5STaqpMmXw0zA=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.0";
    hash = "sha256-QQ8KgU0lu4F5Unh+TbechO//zaAGZ4MfgvW72Cn1hzA=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.1";
    hash = "sha256-fjIJK5jpz99gON2TNpTq2jw3WVtoCFLO9rUvkE/byZU=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.0.11";
    hash = "sha256-KPz1kxe0RUBM+aoktJ/f9p51GudMERU8Pmwm//HdlFg=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.3.0";
    hash = "sha256-rWtdcmcuElNOSzCehflyKwHkDRpiOhJJs8CeQ0l1CCI=";
  })
  (fetchNuGet {
    pname = "Tmds.DBus";
    version = "0.9.0";
    hash = "sha256-w332WVsJrdAOnlSUtgvatSTtnoC81C3LG6J2ip42fW8=";
  })
]
